import { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from '@/context/AuthContext';
import ToastProvider from '@/components/ui/ToastProvider';
import Head from 'next/head';

export const metadata: Metadata = {
  title: "MVP Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="corporate">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
      </head>
      <body className="antialiased" suppressHydrationWarning>
        <AuthProvider>
          {children}
          <ToastProvider />
        </AuthProvider>
      </body>
    </html>
  );
}